# CI de Nível 04 - Disparo dos testes dentro do pipe de dev
name: 'Execução Integrada'

on:
  workflow_dispatch:

jobs:
  inspecao:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Instalar Yarn
        run: npm install -g yarn

      - name: Instalar dependências do projeto
        run: yarn

      - name: Análise de código (lint)
        run: yarn lint
  unidade:
    runs-on: ubuntu-latest
    needs: [inspecao]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Instalar o Yarn
        run: npm install -g yarn

      - name: Instalar dependências do projeto
        run: yarn

      - name: Executar testes unitários
        run: yarn run test
  e2e-tests:
    runs-on: ubuntu-latest
    needs: [inspecao]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Instalar o Yarn
        run: npm install -g yarn

      - name: Instalar dependências do projeto
        run: yarn

      - name: Instalando o Playwright browsers
        run: yarn playwright install

      - name: Executar testes E2E
        run: yarn run e2e

      - name: Carregar o relatório E2E
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: Relatório de testes E2E
          path: ./playwright-report
  deploy:
    runs-on: ubuntu-latest
    needs: [unidade, e2e-tests]
    steps:
      - name: Deploy simulation
        run: echo 'Deploy application'
